// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH8QxVpqt92miUUZyFMRkg2gHK2gMGlfg',
    appId: '1:137306314236:web:715deee454c45387150e79',
    messagingSenderId: '137306314236',
    projectId: 'flutterfire-ui-codelab-8de24',
    authDomain: 'flutterfire-ui-codelab-8de24.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-8de24.firebasestorage.app',
  );

  // Generate this file with credentials with the FlutterFire CLI

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAjPZsDLIJ_f7bQ2lpc5WIdmCsJuZMQp8',
    appId: '1:137306314236:android:7096d3a0cb8a25e1150e79',
    messagingSenderId: '137306314236',
    projectId: 'flutterfire-ui-codelab-8de24',
    storageBucket: 'flutterfire-ui-codelab-8de24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwMCVbSRzGGzSSRCwwIjZ-bdUDp8aUHWA',
    appId: '1:137306314236:ios:f701086f582cf039150e79',
    messagingSenderId: '137306314236',
    projectId: 'flutterfire-ui-codelab-8de24',
    storageBucket: 'flutterfire-ui-codelab-8de24.firebasestorage.app',
    iosClientId: '137306314236-il95sgofh6cdddts1liirnr69dv4os9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.start',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwMCVbSRzGGzSSRCwwIjZ-bdUDp8aUHWA',
    appId: '1:137306314236:ios:f701086f582cf039150e79',
    messagingSenderId: '137306314236',
    projectId: 'flutterfire-ui-codelab-8de24',
    storageBucket: 'flutterfire-ui-codelab-8de24.firebasestorage.app',
    iosClientId: '137306314236-il95sgofh6cdddts1liirnr69dv4os9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.start',
  );

}